[package]
name = "rsocket_rust"
version = "0.5.1"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/rsocket/rsocket-rust"
homepage = "https://github.com/rsocket/rsocket-rust"
description = "rsocket-rust is an implementation of the RSocket protocol in Rust."

[dependencies]
log = "0.4.8"
bytes = "0.5.4"
futures = "0.3.4"
lazy_static = "1.4.0"

[dependencies.tokio]
version = "0.2.16"
default-features = false
features = [ "rt-core", "rt-threaded", "sync", "stream" ]

[features]
default = []
frame = []